[package]
name = "rb64"
description = "Base 64"
version = "0.1.6"
edition = "2021"
authors = ["Saúl Valdelvira <saul@saulv.es>"]
license = "MIT"
readme = "README"

[dependencies]
dbg_unreachable = { version = ">=0.1.2" , git = "https://github.com/saulvaldelvira/dbg-unreachable" }

