[workspace]
resolver = "2"
members = [
    "crates/html",
    "crates/url",
    "crates/mime",
    "crates/http",
    "crates/client",
    "crates/server"
]
default-members = ["crates/server"]

[workspace.dependencies]
http = { package = "http-utils", path = "crates/http", version = ">=0.1.0" }
