workspace = { members = ["src/html", "src/pool", "src/url"] }
[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html = { version = "0.1.0", path = "src/html" }
pool = { version = "0.1.0", path = "src/pool" }
url = { version = "0.1.0", path = "src/url" }
