[package]
name = "job-pool"
description = "Thread Pool"
authors = ["Saúl Valdelvira <saul@saulv.es>"]
version = "0.1.4"
edition = "2021"
license = "MIT"
readme = "README"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
