[package]
name = "rhtml"
description = "Html Utils"
authors = ["Saúl Valdelvira <saul@saulv.es>"]
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-only"
readme = "README"
repository = "https://github.com/saulvaldelvira/http-server"
