[package]
name = "rmime"
description = "MIME Type utils"
version = "0.3.0"
edition = "2024"
authors = ["Saúl Valdelvira <saul@saulv.es>"]
license = "GPL-3.0-only"
readme = "README"
repository = "https://github.com/saulvaldelvira/http-server"
